### ISSUE TITLE
Error: Cannot instantiate interface Magefan\Community\Api\GetModuleVersionInterface - After Magento Upgrade

### ISSUE THREAD

**Issue by iramguir** [magefan/module-community#24]
Hi,

The theme we are using has your Magefan_Community module bundled with it and we are in the process of upgrading our Magento instance of version 2.4.6-p2 running with PHP 8.2.13 , it is a AWS Bitnami instance.

Following the attempted upgrade, following errors are shown in admin after logging in. So far we didnt notice any issue with  frontend. Could you please guide me to resolve this issue. Would upgrading Magefan_Community module resolve it ? is it some issue other than a version incompatibility. As per the module's composer.json its version is 2.1.12

`Error: Cannot instantiate interface Magefan\Community\Api\GetModuleVersionInterface in /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
Stack trace:
#0 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#1 /bitnami/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create()
#2 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#3 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#4 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#5 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(101): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#6 /bitnami/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create()
#7 /bitnami/magento/generated/code/Magefan/Community/Model/AdminNotificationFeedFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create()
#8 /bitnami/magento/app/code/Magefan/Community/Observer/PredispathAdminActionControllerObserver.php(48): Magefan\Community\Model\AdminNotificationFeedFactory->create()
#9 /bitnami/magento/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magefan\Community\Observer\PredispathAdminActionControllerObserver->execute()
#10 /bitnami/magento/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#11 /bitnami/magento/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#12 /bitnami/magento/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#13 /bitnami/magento/vendor/magento/framework/App/FrontController.php(271): Magento\Framework\Event\Manager\Proxy->dispatch()
#14 /bitnami/magento/vendor/magento/framework/App/FrontController.php(211): Magento\Framework\App\FrontController->dispatchPreDispatchEvents()
#15 /bitnami/magento/vendor/magento/framework/App/FrontController.php(146): Magento\Framework\App\FrontController->processRequest()
#16 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#17 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#18 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#19 /bitnami/magento/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#20 /bitnami/magento/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#21 /bitnami/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#22 /bitnami/magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#23 {main}`

Thanking you

Indunil

**Comment by magefan** [comment]
@iramguir ,  to solve the issue please update Magefan_Community to the latest version 2.1.17
